using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class FPSController : MonoBehaviour
{
    private CharacterController controller;
    private Vector3 playerVelocity;
    private bool groundedPlayer;
    private float playerSpeed = 2.0f;
    private float jumpHeight = 1.0f;
    private float gravityValue = -9.81f;


    public float turnSpeed = 4.0f;

    public float minTurnAngle = -45.0f;
    public float maxTurnAngle = 45.0f;
    private float rotX;
    private void Start()
    {
        controller = gameObject.GetComponent<CharacterController>();
    }

    void Update()
    {
        // Skip controls if dialog is active
        if (DialogSystem.IsDialogActive || PauseMenu.IsPaused)
            return;
            
        groundedPlayer = controller.isGrounded;
        if (groundedPlayer && playerVelocity.y < 0)
        {
            playerVelocity.y = 0f;
        }

        Vector3 move = new Vector3(Input.GetAxis("Horizontal"), 0, Input.GetAxis("Vertical"));
        Vector3 transformedInput = Camera.main.transform.TransformDirection(move);
        controller.Move(transformedInput * Time.deltaTime * playerSpeed);

        transform.eulerAngles = Camera.main.transform.eulerAngles;


        // Makes the player jump
        if (Input.GetButtonDown("Jump") && groundedPlayer)
        {
            playerVelocity.y += Mathf.Sqrt(jumpHeight * -2.0f * gravityValue);
        }

        playerVelocity.y += gravityValue * Time.deltaTime;
        controller.Move(playerVelocity * Time.deltaTime);

        MouseAiming();
    }


    void MouseAiming()
    {
        // Skip mouse aiming if dialog is active
        if (DialogSystem.IsDialogActive || PauseMenu.IsPaused)
            return;
            
        // get the mouse inputs
        float y = Input.GetAxis("Mouse X") * turnSpeed;
        rotX += Input.GetAxis("Mouse Y") * turnSpeed;

        // clamp the vertical rotation
        rotX = Mathf.Clamp(rotX, minTurnAngle, maxTurnAngle);

        // rotate the camera
        transform.eulerAngles = new Vector3(-rotX, transform.eulerAngles.y + y, 0);
    }
}